FROM golang:1.24.2 AS builder 

WORKDIR /migrator

COPY go.mod go.sum ./
RUN go mod download

COPY . . 

RUN go build -o migrator ./cmd/migrator/main.go

FROM alpine:latest 

WORKDIR /migrator

COPY --from=builder /migrator/migrator .
COPY ./migrations ./migrations

RUN apk add libc6-compat

CMD ["./migrator", "--migrations-path=./migrations", "--migrations-table=migrations_table"]