services:
  postgres:
    image: postgres:16.8
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  migrator:
    build: 
      context: ../../
      dockerfile: deployment/docker/Dockerfile.migrator
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - url-shortener-network

  app:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - migrator
    networks:
      - url-shortener-network
    
volumes:
  postgres_data:

networks:
  url-shortener-network:
    driver: bridge     