env: "local" # local, dev, prod
app_secret: "test-secret"
http_server:
  address: ":8082"
  timeout: 4s
  idle_timeout: 30s
  user: "my_user"
  password: "my_pass"
sso_server:
  grpc_addr: ":44044"
  grpc_timeout: 5s
  retries: 3
